Fix utimestart being constantly set
CFC-Servers/cfc_time pull request #38
Opened 2022-07-06 17:18 UTC by wrefgtzweve

https://github.com/TeamUlysses/utime/blob/abc8ffb159371f59892ed248d7898ed717ff4bbc/lua/autorun/sv_utime.lua#L30
Should only be set once when the player spawns in

2022-07-07 02:08 UTC, brandonsturgeon requested changes

2022-07-07 02:08 UTC, brandonsturgeon commented on lua/cfc_time/shared/utime_compat.lua
> +        ply:SetNWFloat( "CFC_UTime_Compat_SessionStart", CurTime() )
Set this in the `CFC_Time_PlayerInitialTime` hook and I'll approve 👍

2022-07-11 03:52 UTC, brandonsturgeon requested changes, later dismissed
I thought about it for awhile. I have a good idea that will involve changing some of the deep-down code.

I think the changes I'm proposing will give us the least-bad solution.

2022-07-11 03:52 UTC, brandonsturgeon commented on lua/cfc_time/shared/utime_compat.lua
> +    return self:GetNWFloat( "CFC_UTime_Compat_SessionStart", CurTime() )
```suggestion
    local now = os.time()
    local sessionSeconds = now - self:GetNWFloat( "CFC_Time_SessionStart", now )
    return CurTime() - sessionSeconds
```

2022-07-11 03:52 UTC, brandonsturgeon commented on lua/cfc_time/shared/utime_compat.lua
> +        ply:SetNWFloat( "UTimeStart", CurTime() )
```suggestion
```

2022-08-17 21:45 UTC, plally approved these changes

2022-08-17 21:59 UTC, brandonsturgeon commented
who?

2022-08-17 21:59 UTC, merged